-- SQLite
-- SQLite
-- SQLite
-- SELECT 
--     bpm.id, bpm.content, bpm.user_id, u.username, ur.role_id, r.role_name, u.is_superuser, u.is_staff, bpm.created, bpm.last_edit
-- FROM 
--     studyblog_v1_api_blogpostmodel bpm
-- JOIN 
--     studyblog_v1_api_userprofilemodel u ON bpm.user_id = u.id
-- JOIN
--     studyblog_v1_api_userrolemodel ur ON bpm.user_id = ur.user_id
-- JOIN 
--     studyblog_v1_api_rolemodel r ON ur.role_id = r.id

-- SELECT 
--     * 
-- FROM 
--     studyblog_v1_api_blogpostcommentmodel bpc
-- CROSS JOIN 
--     studyblog_v1_api_blogpostcommentmodel self_bpc ON bpc.id = self_bpc.blogpost_comment_id
SELECT * FROM studyblog_v1_api_blogpostcommentmodel
-- SELECT 
--     * 
-- FROM 
--     studyblog_v1_api_blogpostcommentmodel bpc
-- LEFT JOIN 
--     studyblog_v1_api_blogpostcommentmodel self_bpc ON bpc.id = self_bpc.blogpost_comment_id